name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      # 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup application.properties
        run: |
          touch ./src/main/resources/application.properties
          echo "${{ secrets.CI_APPLICATION }}" > ./src/main/resources/application.properties
          cat ./src/main/resources/application.properties

      # gradlew 권한 추가
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      # JDK 21 세팅
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Gradle 캐시 복원
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
              ${{ runner.os }}-gradle-


      # Gradle test and build
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Test With Gradle Wrapper
        run: ./gradlew test

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      # checkstyle 검사
      - name: Run java checkstyle
        uses: nikitasavinov/checkstyle-action@0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'Checkstyle'
          checkstyle_config: ./config/naver-checkstyle-rules.xml
          properties_file: ./config/naver-checkstyle-suppressions.xml

      # Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 메타데이터 추출
      - name: Extract Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/sonisori-be
          tags: |
            type=sha,prefix=
            type=ref,event=branch

      # Docker 이미지 빌드 및 push
      - name: Build and Push Docker image
#        if: github.event_name == 'push'
        run: |
          touch ./src/main/resources/application.properties
          echo "${{ secrets.DOCKER_APPLICATION }}" > ./src/main/resources/application.properties
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/sonisori-be:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sonisori-be:latest
